apiVersion: v1
kind: Service
metadata:
  name: payment
  namespace: roboshop
spec:
  type: {{ .Values.service.type }}
  selector:
    project: roboshop
    component: payment
    tier: backend
  ports:
    - protocol: TCP
      port: 8080 # service port
      targetPort: 8080 # container port