apiVersion: v1
kind: Service
metadata:
  name: cart
  namespace: roboshop
spec:
  type: {{ .Values.service.type }}
  selector:
    project: roboshop
    component: cart
    tier: backend
  ports:
    - protocol: TCP
      port: 8080 #serive port
      targetPort: 8080  #container port
